/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package noempat;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ikhsan15
 */
public class NoEmpat extends javax.swing.JFrame {

    /**
     * Creates new form NoEmpat
     */
    public NoEmpat() {
        initComponents();
//        jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrouptype = new javax.swing.ButtonGroup();
        btngroupkategori = new javax.swing.ButtonGroup();
        btngrouplokasi = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtiditem = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdokategori1 = new javax.swing.JRadioButton();
        txtkategori = new javax.swing.JTextField();
        rdokategori2 = new javax.swing.JRadioButton();
        cmblokasi = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdounit = new javax.swing.JRadioButton();
        rdosparepart = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdokolasi1 = new javax.swing.JRadioButton();
        txtlokasi = new javax.swing.JTextField();
        rdolokasi2 = new javax.swing.JRadioButton();
        cmbkategori = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Kelola Item");
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("IDItem");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nama");

        txtiditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtiditemActionPerformed(evt);
            }
        });

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kategori");

        btngroupkategori.add(rdokategori1);
        rdokategori1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdokategori1.setText("Input New Category");
        rdokategori1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdokategori1ActionPerformed(evt);
            }
        });

        txtkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkategoriActionPerformed(evt);
            }
        });

        btngroupkategori.add(rdokategori2);
        rdokategori2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdokategori2.setText("Use Exiting Category");
        rdokategori2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdokategori2ActionPerformed(evt);
            }
        });

        cmblokasi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmblokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblokasiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quantity");

        txtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantityActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Harga");

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Type");

        btngrouptype.add(rdounit);
        rdounit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdounit.setText("Unit");
        rdounit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdounitActionPerformed(evt);
            }
        });

        btngrouptype.add(rdosparepart);
        rdosparepart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdosparepart.setText("Sparepart");
        rdosparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdosparepartActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("jLabel7");

        btngrouplokasi.add(rdokolasi1);
        rdokolasi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdokolasi1.setText("Input New Category");
        rdokolasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdokolasi1ActionPerformed(evt);
            }
        });

        txtlokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlokasiActionPerformed(evt);
            }
        });

        btngrouplokasi.add(rdolokasi2);
        rdolokasi2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rdolokasi2.setText("Use Exiting Category");
        rdolokasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdolokasi2ActionPerformed(evt);
            }
        });

        cmbkategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkategoriActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Lokasi");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(44, 44, 44)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cmbkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtnama)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdokategori2)
                            .addComponent(rdokategori1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(rdounit)
                                .addGap(35, 35, 35)
                                .addComponent(rdosparepart)
                                .addGap(18, 18, 18))
                            .addComponent(rdokolasi1)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmblokasi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtkategori)
                                    .addComponent(txtlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rdolokasi2)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(txtiditem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtiditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdokategori1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdokategori2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdounit)
                    .addComponent(rdosparepart))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdokolasi1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtlokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(rdolokasi2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmblokasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(591, Short.MAX_VALUE))
        );

        jMenu1.setText("Edit");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mater Data");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtiditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiditemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiditemActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void rdokategori1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdokategori1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdokategori1ActionPerformed

    private void txtkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkategoriActionPerformed

    private void rdokategori2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdokategori2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdokategori2ActionPerformed

    private void cmbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkategoriActionPerformed

    private void txtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantityActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void rdounitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdounitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdounitActionPerformed

    private void rdokolasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdokolasi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdokolasi1ActionPerformed

    private void txtlokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlokasiActionPerformed

    private void rdolokasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdolokasi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdolokasi2ActionPerformed

    private void cmblokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblokasiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        txtiditem.setText(txtiditem.getText());
        txtnama.setText(txtnama.getText());
        cmbkategori.getSelectedItem().toString();
        txtquantity.setText(txtquantity.getText());
        txtharga.setText(txtharga.getText());
//        rdotype.setText(rdotype.getText());
//        cmbprodi.getSelectedItem().toString();
//        txtalamat.setText(txtalamat.getText());
        
        txtiditem.setEnabled(false);
        txtnama.setEnabled(false);        
//        txtkategori.setEnabled(false);
        txtquantity.setEnabled(false);
        txtharga.setEnabled(false);
        
        String kategori;
        if(rdokategori1.isSelected()){
            kategori = txtkategori.getText();
        }else{
            kategori = cmbkategori.getSelectedItem().toString();
        }
        
        String type;
        if(rdounit.isSelected()){
            type = "Unit";
        }else{
            type = "Sparepart";
        }
        
        String lokasi;
        if(rdokolasi1.isSelected()){
            lokasi = txtlokasi.getText();
        }else{
            lokasi = cmblokasi.getSelectedItem().toString();
        }
        
//        cmbprodi.setEnabled(false);
//        txtalamat.setEnabled(false);
//        txthasil.setEnabled(false);
        jButton1.setEnabled(false);
        {
            NoEmpat tampil = new NoEmpat();
            String pesan[] = {
                "IDITEM   : " + txtiditem.getText(),
                "NAMA    : " + txtnama.getText(),
                "KATEGORI  : " + kategori,
                "QUANTITY  : " + txtquantity.getText(),
                "HARGA  : " + txtharga.getText(),
                "TYPE      : " + type,
                "LOKASI      : " + lokasi,
//                "PRODI  : " + cmbprodi.getSelectedItem(),
//                "ALAMAT : " + txtalamat.getText()
            };
            
            JOptionPane.showMessageDialog(tampil, pesan);
            
            {if(evt.getID() == 
                    KeyEvent.VK_ENTER){
                    jButton1.doClick();
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdosparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdosparepartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdosparepartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoEmpat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoEmpat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoEmpat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoEmpat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoEmpat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngroupkategori;
    private javax.swing.ButtonGroup btngrouplokasi;
    private javax.swing.ButtonGroup btngrouptype;
    private javax.swing.JComboBox cmbkategori;
    private javax.swing.JComboBox cmblokasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton rdokategori1;
    private javax.swing.JRadioButton rdokategori2;
    private javax.swing.JRadioButton rdokolasi1;
    private javax.swing.JRadioButton rdolokasi2;
    private javax.swing.JRadioButton rdosparepart;
    private javax.swing.JRadioButton rdounit;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtiditem;
    private javax.swing.JTextField txtkategori;
    private javax.swing.JTextField txtlokasi;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
